import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Image, Linking, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router, useFocusEffect } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { euro, getListings, originalListing, type Listing } from "../lib/api";
import { blockedPhones } from "../lib/blocked";

export default function Home() {
  const [items, setItems] = useState<Listing[]>([originalListing]);
  const [query, setQuery] = useState("");
  const [mode, setMode] = useState("all");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [blocked, setBlocked] = useState<string[]>([]);
  useFocusEffect(useCallback(() => { setBlocked(blockedPhones()); }, []));
  async function refresh() { setLoading(true); try { setItems(await getListings()); setError(""); } catch(e) { setError(e instanceof Error ? e.message : "Nu s-au putut încărca anunțurile."); } finally { setLoading(false); } }
  useEffect(() => { let active=true; getListings().then(rows=>{if(active)setItems(rows)}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Nu s-au putut încărca anunțurile.")}); return ()=>{active=false}; }, []);
  const filtered = items.filter(p => !blocked.includes(p.phone) && (mode === "all" || p.transaction === mode) && `${p.name} ${p.area}`.toLocaleLowerCase("ro").includes(query.trim().toLocaleLowerCase("ro")));
  return <SafeAreaView style={styles.safe} edges={["bottom"]}><ScrollView contentContainerStyle={styles.container} refreshControl={<RefreshControl refreshing={loading} onRefresh={refresh}/> }><View style={styles.hero}><Text style={styles.eyebrow}>DUMITRU IMOBILIARE · ROMÂNIA</Text><Text style={styles.heroTitle}>Găsește locul potrivit pentru tine.</Text><Text style={styles.heroSub}>Caută locuințe din toată țara sau publică un anunț gratuit.</Text><Pressable style={styles.goldButton} onPress={() => router.push("/publish")}><Text style={styles.goldText}>＋ Publică anunț</Text></Pressable></View><TextInput value={query} onChangeText={setQuery} placeholder="Oraș, cartier, proprietate…" placeholderTextColor="#82909e" style={styles.search} accessibilityLabel="Caută proprietăți"/><View style={styles.tabs}>{[["all","Toate"],["vanzare","Cumpără"],["inchiriere","Închiriază"]].map(([value,label])=><Pressable key={value} onPress={()=>setMode(value)} style={[styles.tab,mode===value&&styles.tabActive]}><Text style={[styles.tabText,mode===value&&styles.tabTextActive]}>{label}</Text></Pressable>)}</View><View style={styles.heading}><Text style={styles.headingText}>Proprietăți</Text><Text style={styles.count}>{filtered.length} rezultate</Text></View>{error ? <Text style={styles.error}>{error}</Text> : null}{loading && items.length===0 ? <ActivityIndicator color="#b88b4e"/> : null}{filtered.map(item=><Pressable key={item.id} style={styles.card} onPress={()=>router.push({pathname:"/listing/[id]",params:{id:item.id}})}><Image alt={`Fotografie ${item.name}`} source={{uri:item.photos[0]}} style={styles.photo}/><View style={styles.cardBody}><Text style={styles.badge}>{item.transaction==="vanzare" ? "VÂNZARE" : "ÎNCHIRIERE"}</Text><Text style={styles.cardTitle}>{item.name}</Text><Text style={styles.location}>⌖ {item.area}</Text><Text style={styles.meta}>{item.rooms ? `${item.rooms} camere` : "Teren"}{item.size ? ` · ${item.size} m²` : ""}</Text><Text style={styles.price}>{euro(item.price)}{item.transaction==="inchiriere" ? " / lună" : ""}</Text></View></Pressable>)}{!filtered.length&&<Text style={styles.empty}>Nu sunt rezultate pentru această căutare.</Text>}<Pressable onPress={()=>Linking.openURL("https://dumitru-imobiliare.bogdan-dum.chatgpt.site/confidentialitate.html")}><Text style={styles.privacy}>Confidențialitate</Text></Pressable><Pressable onPress={()=>Linking.openURL("tel:0758408604")}><Text style={styles.contact}>Contactează agenția · 0758 408 604</Text></Pressable></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({safe:{flex:1},container:{padding:17,paddingBottom:40},hero:{backgroundColor:"#142337",borderRadius:20,padding:25,marginBottom:20},eyebrow:{color:"#d6ad75",fontWeight:"800",fontSize:12,letterSpacing:1},heroTitle:{fontFamily:"serif",fontSize:34,color:"white",marginTop:14,lineHeight:39},heroSub:{fontSize:15,color:"#c7d1dc",marginVertical:15,lineHeight:22},goldButton:{backgroundColor:"#c39a5d",borderRadius:10,padding:13,alignSelf:"flex-start"},goldText:{fontWeight:"800",color:"#142337",fontSize:15},search:{backgroundColor:"white",borderRadius:12,borderWidth:1,borderColor:"#dce3e9",height:50,paddingHorizontal:15,fontSize:16,color:"#142337"},tabs:{flexDirection:"row",gap:6,marginTop:14,marginBottom:22},tab:{paddingVertical:10,paddingHorizontal:14,backgroundColor:"#e9edf0",borderRadius:9},tabActive:{backgroundColor:"#142337"},tabText:{color:"#5c6b7a",fontWeight:"700",fontSize:13},tabTextActive:{color:"white"},heading:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:13},headingText:{fontFamily:"serif",fontSize:26,color:"#142337"},count:{color:"#758395"},card:{backgroundColor:"white",borderRadius:16,overflow:"hidden",marginBottom:18,borderWidth:1,borderColor:"#e3e8ec"},photo:{height:190,width:"100%",backgroundColor:"#dbe0e4"},cardBody:{padding:17},badge:{fontSize:11,color:"#a0763e",fontWeight:"900",letterSpacing:1},cardTitle:{fontSize:18,fontWeight:"700",color:"#17283c",marginTop:7},location:{color:"#68788a",marginTop:7},meta:{color:"#68788a",marginTop:9},price:{fontSize:21,fontWeight:"800",color:"#17283c",marginTop:14},error:{color:"#9f3434",marginBottom:12},empty:{color:"#68788a",textAlign:"center",padding:30},privacy:{textAlign:"center",color:"#7b654a",paddingTop:25,paddingBottom:12},contact:{textAlign:"center",color:"#74512e",paddingBottom:24,fontSize:15}});
